In [1]:
import numpy as np

u = np.array([2, -1, 5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6, 2, 0, 3])

x = 2 * u - (v + 3 * w)

print(x)

[ 18 -11   9  -8]


In [2]:
import numpy as np

u = np.array([2, -1, 5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6, 2, 0, 3])

x = 0.5 * (2 * u - v - 3 * w)

print(x)

[ 9.  -5.5  4.5 -4. ]


In [3]:
from numpy import linalg
import numpy as np

A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])

X = np.linalg.solve(A, B)

print(X)

[ 1. -2. -1.]


In [4]:
import numpy as np
from numpy import linalg as LA

A = np.matrix([[1, 0], [0, 0]])
B = np.matrix([[0, 0], [0, 1]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[1 0]
 [0 0]]

Matrix B:
 [[0 0]
 [0 1]]


In [5]:
LA.inv(A+B)

matrix([[1., 0.],
        [0., 1.]])

In [6]:
 LA.det(A)

np.float64(0.0)

In [7]:
LA.det(B)

np.float64(0.0)

In [8]:
LA.det(A+B)

np.float64(1.0)

In [9]:
import sympy as sp

x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])

x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])

x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])

print(A1.T)

Matrix([[x1, y1], [y1, x1]])


In [10]:
 (A1+A2).T

Matrix([
[x1 + x2, y1 + y2],
[y1 + y2, x1 + x2]])

In [11]:
((A1+A2).T).equals(A1+A2)

True

In [12]:
import sympy as sp

x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])

c = sp.symbols('c')

print(c * A)

Matrix([[c*x, c*y], [c*y, c*x]])


In [13]:
((c*A).T).equals(c*A)

True

In [14]:
import sympy as sp

c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')

sp.solve([c1 + c2 - u1, c1 - c2 - u2])

{c1: u1/2 + u2/2, c2: u1/2 - u2/2}

In [15]:
import sympy as sp

c1, c2 = sp.symbols('c1 c2')
u1 = 0
u2 = 0

solution = sp.solve([c1 + c2 - u1, c1 - c2 - u2], (c1, c2))
print(solution)

{c1: 0, c2: 0}


In [16]:
import numpy as np

P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])

P_caua = (P.T + vecdelta).T

print(P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


In [17]:
import numpy as np

P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],
                           [ 0.0, 2.0]])

P_caub = (P.T @ matran_biendoi + vecdelta).T

print(P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


In [18]:
import sympy as sp
from sympy import lambdify

x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')

a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')

result_f1_abc = f1(a, b, c)

print(result_f1_abc)

a - b + c


In [19]:
f1(d, e, f)

d - e + f

In [20]:
f1(a+d, b+e, c+f)

a - b + c + d - e + f

In [21]:
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)

True

In [22]:
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))

True

In [23]:
import sympy as sp
from sympy import lambdify

# Define symbolic variables
x1, x2, x3 = sp.symbols('x1 x2 x3')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
q = sp.symbols('q')

# Define the expression and lambdify it
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'sympy') # Use 'sympy' for symbolic evaluation

# Test the linearity property
# Left-hand side of the equation
lhs = q * f1(a, b, c) + f1(d, e, f)

# Right-hand side of the equation
rhs = f1(q * a + d, q * b + e, q * c + f).expand()

# Check if both sides are equal
print(lhs.equals(rhs))

True


In [24]:
import sympy as sp
from sympy import lambdify

x1, x2, x3 = sp.symbols('x1 x2 x3')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
q = sp.symbols('q')

bieuthuc2 = 2 * x2 + 3 * x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'sympy')

lhs_f2 = q * f2(a, b, c) + f2(d, e, f)
rhs_f2 = f2(q * a + d, q * b + e, q * c + f).expand()

print(lhs_f2.equals(rhs_f2))

True


In [25]:
import sympy as sp

a, b = sp.symbols('a b')
x, y = sp.symbols('x y')

# Solve the system of equations:
# a + 3b = x
# 2a + 5b = y
solution = sp.solve([a + 3 * b - x, 2 * a + 5 * b - y], [a, b])

print(solution)

{a: -5*x + 3*y, b: 2*x - y}


In [26]:
import numpy as np
import sympy as sp

a, b = sp.symbols('a b')

fu1 = np.array([1, 1, 2])
fu2 = np.array([4, 2, 1])

fu = a * fu1 + b * fu2

print(fu)

[a + 4*b a + 2*b 2*a + b]


In [27]:
import numpy as np
import sympy as sp

a, b, x, y = sp.symbols('a b x y')

fu1 = np.array([1, 1, 2])
fu2 = np.array([4, 2, 1])

fu = a.subs(a, -5*x + 3*y) * fu1 + b.subs(b, 2*x - y) * fu2

print(fu)

[3*x - y -x + y -8*x + 5*y]


In [28]:
import sympy as sp

def g(x_sym, y_sym, z_sym):
    return sp.Matrix([x_sym + y_sym + z_sym, 0])

x1, y1, z1 = sp.symbols('x1 y1 z1')
x2, y2, z2 = sp.symbols('x2 y2 z2')

u_vec = (x1, y1, z1)
v_vec = (x2, y2, z2)

g_u = g(u_vec[0], u_vec[1], u_vec[2])
g_v = g(v_vec[0], v_vec[1], v_vec[2])

sum_g_uv = g_u + g_v
print("g(u) + g(v) =\n", sum_g_uv)

u_plus_v = (u_vec[0] + v_vec[0], u_vec[1] + v_vec[1], u_vec[2] + v_vec[2])

g_u_plus_v = g(u_plus_v[0], u_plus_v[1], u_plus_v[2])
print("\ng(u + v) =\n", g_u_plus_v)

is_additive = (sum_g_uv.simplify() == g_u_plus_v.simplify())
print("\nTính chất cộng (g(u + v) == g(u) + g(v)): ", is_additive)

c = sp.symbols('c')

c_u_vec = (c * x1, c * y1, c * z1)
g_c_u = g(c_u_vec[0], c_u_vec[1], c_u_vec[2])
print("\ng(c * u) =\n", g_c_u)

c_times_g_u = c * g(x1, y1, z1)
print("\nc * g(u) =\n", c_times_g_u)

is_homogeneous = (g_c_u.simplify() == c_times_g_u.simplify())
print("\nTính chất nhân với vô hướng (g(c*u) == c*g(u)): ", is_homogeneous)

if is_additive and is_homogeneous:
    print("\nKết luận: Ánh xạ g(x, y, z) = (x + y + z, 0) LÀ một ánh xạ tuyến tính.")
else:
    print

g(u) + g(v) =
 Matrix([[x1 + x2 + y1 + y2 + z1 + z2], [0]])

g(u + v) =
 Matrix([[x1 + x2 + y1 + y2 + z1 + z2], [0]])

Tính chất cộng (g(u + v) == g(u) + g(v)):  True

g(c * u) =
 Matrix([[c*x1 + c*y1 + c*z1], [0]])

c * g(u) =
 Matrix([[c*(x1 + y1 + z1)], [0]])

Tính chất nhân với vô hướng (g(c*u) == c*g(u)):  True

Kết luận: Ánh xạ g(x, y, z) = (x + y + z, 0) LÀ một ánh xạ tuyến tính.


In [29]:
import numpy as np

transformation_matrix = np.array([[0, 1],
                                  [1, -1]])

original_square_points = np.array([[0, 1, 1, 0, 0],
                                   [0, 0, 1, 1, 0]])

transformed_points = transformation_matrix @ original_square_points

F_point = np.array([[0.5],
                    [0.5]])

transformed_F = transformation_matrix @ F_point

print("Ma trận biến đổi:\n", transformation_matrix)
print("\nCác điểm của hình đã biến đổi:\n", transformed_points)
print(f"\nĐiểm F ban đầu: ({F_point[0,0]}, {F_point[1,0]})")
print(f"Điểm F sau biến đổi: ({transformed_F[0,0]}, {transformed_F[1,0]})")

Ma trận biến đổi:
 [[ 0  1]
 [ 1 -1]]

Các điểm của hình đã biến đổi:
 [[ 0  0  1  1  0]
 [ 0  1  0 -1  0]]

Điểm F ban đầu: (0.5, 0.5)
Điểm F sau biến đổi: (0.5, 0.0)


In [30]:
import sympy as sp

def T_mapping(x, y):
    return sp.Matrix([x - y, x + 2*y])

# Kiểm tra tính chất cộng
u1, u2, w1, w2 = sp.symbols('u1 u2 w1 w2')
lhs_add = T_mapping(u1 + w1, u2 + w2)
rhs_add = T_mapping(u1, u2) + T_mapping(w1, w2)
is_additive = lhs_add.equals(rhs_add)

# Kiểm tra tính chất nhân với vô hướng
c = sp.symbols('c')
lhs_hom = T_mapping(c * u1, c * u2)
rhs_hom = c * T_mapping(u1, u2)
is_homogeneous = lhs_hom.equals(rhs_hom)

# Kết luận
if is_additive and is_homogeneous:
    print("Ánh xạ T(v1, v2) = (v1 - v2, v1 + 2v2) LÀ một ánh xạ tuyến tính.")
else:
    print("Ánh xạ T(v1, v2) = (v1 - v2, v1 + 2v2) KHÔNG phải là một ánh xạ tuyến tính.")

Ánh xạ T(v1, v2) = (v1 - v2, v1 + 2v2) LÀ một ánh xạ tuyến tính.


In [31]:
import sympy as sp

a, b, c, d, e, f = sp.symbols('a b c d e f')
x, y = sp.symbols('x y')
x_prime, y_prime = sp.symbols("x' y'")
theta = sp.symbols('theta')

conic_general = a*x**2 + b*x*y + c*y**2 + d*x + e*y + f

A_matrix = sp.Matrix([[a, b/2], [b/2, c]])
X_vector = sp.Matrix([[x], [y]])

matrix_form_conic = (X_vector.T @ A_matrix @ X_vector)[0,0] + (sp.Matrix([[d, e]]) @ X_vector)[0,0] + f

print("Phương trình conic ban đầu (dạng tổng quát):")
print(conic_general)
print("\nPhương trình conic dưới dạng ma trận (X^T A X + [d e] X + f):\n", matrix_form_conic)

print("\n--- Phân tích Góc Quay ---")

eigenvalues_A = A_matrix.eigenvals()
print(f"Các giá trị riêng của A (λ1, λ2): {list(eigenvalues_A.keys())}")

eigenvectors_A_info = A_matrix.eigenvects()

try:
    v1_normalized = eigenvectors_A_info[0][2][0].normalize()
    if len(eigenvectors_A_info) > 1:
        v2_normalized = eigenvectors_A_info[1][2][0].normalize()
    else:
        v2_normalized = sp.Matrix([-v1_normalized[1], v1_normalized[0]]).normalize()
    P_matrix = sp.Matrix.hstack(v1_normalized, v2_normalized)
    print("\nMa trận P (ma trận quay từ các vector riêng chuẩn hóa):\n", P_matrix)
except Exception:
    P_matrix = sp.Matrix([[sp.cos(theta), -sp.sin(theta)], [sp.sin(theta), sp.cos(theta)]])
    print("\nMa trận P (dạng lý thuyết nếu không thể tự xây dựng):\n", P_matrix)

lambda1_val = list(eigenvalues_A.keys())[0] if eigenvalues_A else sp.symbols('lambda1')
lambda2_val = list(eigenvalues_A.keys())[1] if len(eigenvalues_A) > 1 else sp.symbols('lambda2')

rotated_quadratic_part = lambda1_val * x_prime**2 + lambda2_val * y_prime**2

print(f"\nDạng bậc hai sau khi quay trục: {rotated_quadratic_part}")

Phương trình conic ban đầu (dạng tổng quát):
a*x**2 + b*x*y + c*y**2 + d*x + e*y + f

Phương trình conic dưới dạng ma trận (X^T A X + [d e] X + f):
 d*x + e*y + f + x*(a*x + b*y/2) + y*(b*x/2 + c*y)

--- Phân tích Góc Quay ---
Các giá trị riêng của A (λ1, λ2): [a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2, a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2]

Ma trận P (dạng lý thuyết nếu không thể tự xây dựng):
 Matrix([[cos(theta), -sin(theta)], [sin(theta), cos(theta)]])

Dạng bậc hai sau khi quay trục: x'**2*(a/2 + c/2 - sqrt(a**2 - 2*a*c + b**2 + c**2)/2) + y'**2*(a/2 + c/2 + sqrt(a**2 - 2*a*c + b**2 + c**2)/2)
