bài tập trên lớp

In [ ]:
def scale(a, v):

  return [a * vi for vi in v]


v = [3, 5, 7]
result = scale(10, v)
print(result)

[30, 50, 70]


In [ ]:
def sumvector(v, w):

  return [vi + wi for (vi, wi) in zip(v, w)]


v = [3, 5, 7]
w = [2, 4, 6]
result = sumvector(v, w)
print(result)

[5, 9, 13]


In [ ]:
def dotvector(v, w):
  products = [vi * wi for (vi, wi) in zip(v, w)]
  return sum(products)
v = [3, 5, 7]
w = [2, 4, 6]
result = dotvector(v, w)
print(result)

68


In [ ]:
import math
def dotvector(v, w):
  return sum([vi * wi for (vi, wi) in zip(v, w)])
def lenvector(v):
  dot_product_vv = dotvector(v, v)
  return math.sqrt(dot_product_vv)
w = [2, 4, 6]
length_of_w = lenvector(w)
print(f"Chiều dài của vector w {w} là: {length_of_w}")
v = [3, 5, 7]
length_of_v = lenvector(v)
print(f"Chiều dài của vector v {v} là: {length_of_v}")

Chiều dài của vector w [2, 4, 6] là: 7.483314773547883
Chiều dài của vector v [3, 5, 7] là: 9.1104335791443


In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print("Mảng scores ban đầu:")
print(scores)
print("\nKết quả scores >= 0:")
print(scores >= 0)
print("\nKết quả scores < 0:")
print(scores < 0)
print("\nKết quả sử dụng np.select:")
print(np.select([scores >= 0, scores < 0], ['so duong', 'so am'], default=''))

Mảng scores ban đầu:
[-1  1  2 -3  5 -4]

Kết quả scores >= 0:
[False  True  True False  True False]

Kết quả scores < 0:
[ True False False  True False  True]

Kết quả sử dụng np.select:
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [ ]:
import numpy as np

scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print("Mảng scores ban đầu:")
print(scores)

print("\nKết quả sử dụng np.select với 3 điều kiện:")

result = np.select([scores > 0, scores == 0, scores < 0], ['so duong', 'so 0', 'so am'], default='')
print(result)

Mảng scores ban đầu:
[-1  1  2  0 -3  5  0 -4]

Kết quả sử dụng np.select với 3 điều kiện:
['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


In [ ]:
import numpy as np
from scipy import linalg, sparse
D = np.asmatrix([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [ ]:

C = np.asmatrix(np.random.random((5, 7)))
print(C)

[[0.20131779 0.17226367 0.32121752 0.06502579 0.29238684 0.81130361
  0.31874972]
 [0.10281795 0.29259282 0.59418686 0.31523611 0.06756316 0.44025283
  0.32640887]
 [0.06341934 0.46505559 0.74505945 0.10958074 0.08934391 0.4260512
  0.00158478]
 [0.11858551 0.77972386 0.9273475  0.56088986 0.71162225 0.52062623
  0.84696394]
 [0.80427264 0.27597842 0.12287488 0.76756832 0.23538867 0.44751481
  0.40021333]]


In [ ]:

A = np.asmatrix(np.random.random((2, 2)))
print(A)

[[0.86483987 0.12234906]
 [0.15538963 0.01246418]]


In [ ]:

from scipy import linalg, sparse
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print("Giá trị của b (ndarray):")
print(b)
print("\nGiá trị của B (matrix):")
print(B)


Giá trị của b (ndarray):
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

Giá trị của B (matrix):
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [ ]:

A = np.asmatrix(np.random.random((2, 2)))
print("Ma trận A ban đầu:")
print(A)
print("\nMa trận chuyển vị A.T:")
A_T = A.T
print(A_T)
print("\nMa trận nghịch đảo A.I:")
try:
    A_I = A.I
    print(A_I)
except np.linalg.LinAlgError:
    print("Ma trận A không khả nghịch (singular), không thể tính nghịch đảo.")

Ma trận A ban đầu:
[[0.98380072 0.38711244]
 [0.8779089  0.92857016]]

Ma trận chuyển vị A.T:
[[0.98380072 0.8779089 ]
 [0.38711244 0.92857016]]

Ma trận nghịch đảo A.I:
[[ 1.61862456 -0.67478984]
 [-1.53031507  1.71489896]]


In [ ]:

from scipy import linalg
A = np.array([ [3, 1, 2], [0, 5, 1], [4, -1, 3] ])
print("Ma trận A dùng cho linalg.inv:")
print(A)
print("\nMa trận nghịch đảo của A (sử dụng linalg.inv):")
try:
    A_inv = linalg.inv(A)
    print(A_inv)
except np.linalg.LinAlgError:
    print("Ma trận A không khả nghịch (singular), không thể tính nghịch đảo bằng linalg.inv.")
M = np.array([[-1,3,2],[0,2,1],[1,5,-2]])
print("\nMa trận M đã định nghĩa:")
print(M)

Ma trận A dùng cho linalg.inv:
[[ 3  1  2]
 [ 0  5  1]
 [ 4 -1  3]]

Ma trận nghịch đảo của A (sử dụng linalg.inv):
[[ 1.33333333 -0.41666667 -0.75      ]
 [ 0.33333333  0.08333333 -0.25      ]
 [-1.66666667  0.58333333  1.25      ]]

Ma trận M đã định nghĩa:
[[-1  3  2]
 [ 0  2  1]
 [ 1  5 -2]]


In [ ]:

M = np.array([[-1, 3, 2],
              [ 0, 2, 1],
              [ 1, 5,-2]])
M_lower = np.tril(M)
print(M_lower)
M = np.array([[-1,3,2],[0,2,1],[1,5,-2]])

[[-1  0  0]
 [ 0  2  0]
 [ 1  5 -2]]


In [ ]:

M = np.array([[-1, 3, 2],
              [ 0, 2, 1],
              [ 1, 5,-2]])
M_upper = np.triu(M)
print(M_upper)
M = np.array([[-1,3,2],[0,2,1],[1,5,-2]])

[[-1  3  2]
 [ 0  2  1]
 [ 0  0 -2]]


In [ ]:

M = np.array([[-1, 3, 2],
              [ 0, 2, 1],
              [ 1, 5,-2]])
v_diag = np.diag(M)
print(v_diag)
M_diag = np.diag(v_diag)
print(M_diag)

[-1  2 -2]
[[-1  0  0]
 [ 0  2  0]
 [ 0  0 -2]]


In [ ]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
equations = [
    x**2 + 2 - 6,
    y - 1 - 6,
    x + z - 1,
    2*x**2 - 8,
    z**2 + 4 - 5,
    y - z - 8
]

solution = sp.solve(equations, [x, y, z])
print(solution)

[(2, 7, -1)]


In [ ]:
import numpy as np

A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)
print("\nMa trận đơn vị 6x6:")
I = np.eye(6)
print(I)
B = np.zeros((6, 6))
print("\nMa trận B ban đầu (zeroes):")
print(B)
B[0:3, 0:3] = A[0:3, 0:3]
B[3:6, 0:3] = A[3:6, 0:3]
B[0:3, 3:6] = A[0:3, 3:6]
B[3:6, 3:6] = A[3:6, 3:6]
A_flat = A.flatten()
B[0:3, 0:3] = A_flat[0:9].reshape(3, 3)
B[0:3, 3:6] = A_flat[9:18].reshape(3, 3)
B[3:6, 0:3] = A_flat[18:27].reshape(3, 3)
B[3:6, 3:6] = A_flat[27:36].reshape(3, 3)
print("\nMa trận B sau khi gán các khối:")
print(B)


Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận đơn vị 6x6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Ma trận B ban đầu (zeroes):
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Ma trận B sau khi gán các khối:
[[ 0.  1.  2.  9. 10. 11.]
 [ 3.  4.  5. 12. 13. 14.]
 [ 6.  7.  8. 15. 16. 17.]
 [18. 19. 20. 27. 28. 29.]
 [21. 22. 23. 30. 31. 32.]
 [24. 25. 26. 33. 34. 35.]]


In [ ]:
import numpy as np
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
size_of_A = A.size
print(size_of_A)

6


In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A_matrix = np.asmatrix(A)
diagonal_elements = np.matrix.diagonal(A_matrix)
print(diagonal_elements)

[[1 5 9]]


In [ ]:
import numpy as np
A = np.array([
    [0, 1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10, 11],
    [12, 13, 14, 15, 16, 17],
    [18, 19, 20, 21, 22, 23],
    [24, 25, 26, 27, 28, 29],
    [30, 31, 32, 33, 34, 35]
])
I6 = np.identity(6)
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
import numpy as np
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)
vecB = np.array([[1., 2., 3., 4., 5., 6.]]).T
print("\nVector vecB:")
print(vecB)
C = A.dot(vecB)
print("\nKết quả C = A.dot(vecB):")
print(C)
D = np.array([[1., 2., 3., 4., 5., 6.],
              [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D:")
print(D)
E = A.dot(D.T)
print("\nKết quả E = A.dot(D.T) (hoặc D.dot(A) nếu muốn):")
print(E)
F = np.zeros((6, 2))
print("\nMa trận F kích thước 6x2 (ví dụ ma trận zeros):")
print(F)

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Vector vecB:
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]

Kết quả C = A.dot(vecB):
[[ 70.]
 [196.]
 [322.]
 [448.]
 [574.]
 [700.]]

Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]

Kết quả E = A.dot(D.T) (hoặc D.dot(A) nếu muốn):
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]

Ma trận F kích thước 6x2 (ví dụ ma trận zeros):
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np

A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

D = np.array([[1., 2., 3., 4., 5., 6.],
              [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D:")
print(D)

try:
    E_invalid = A.dot(D)
    print(E_invalid)
except ValueError as e:
    print(f"Lỗi: {e}.")
    print("Không thể thực hiện phép nhân A.dot(D) vì kích thước không tương thích.")
    print("Để nhân ma trận A (6x6) và D (2x6) một cách hợp lệ, bạn có thể thử:")
    print("1. Tính E = D.dot(A) (kích thước kết quả 2x6)")
    print("2. Tính E = A.dot(D.T) (kích thước kết quả 6x2)")

print("\nTính tích ma trận E = A.dot(D.T) (A 6x6, D.T 6x2):")
E_valid_1 = A.dot(D.T)
print(E_valid_1)

print("\nTính tích ma trận E = D.dot(A) (D 2x6, A 6x6):")
E_valid_2 = D.dot(A)
print(E_valid_2)

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận D:
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
Lỗi: shapes (6,6) and (2,6) not aligned: 6 (dim 1) != 2 (dim 0).
Không thể thực hiện phép nhân A.dot(D) vì kích thước không tương thích.
Để nhân ma trận A (6x6) và D (2x6) một cách hợp lệ, bạn có thể thử:
1. Tính E = D.dot(A) (kích thước kết quả 2x6)
2. Tính E = A.dot(D.T) (kích thước kết quả 6x2)

Tính tích ma trận E = A.dot(D.T) (A 6x6, D.T 6x2):
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]

Tính tích ma trận E = D.dot(A) (D 2x6, A 6x6):
[[420. 441. 462. 483. 504. 525.]
 [ 36.  39.  42.  45.  48.  51.]]


In [ ]:
import numpy as np

A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

F = np.array([[1., 1.],
              [2., 0.],
              [3., 1.],
              [4., 0.],
              [5., 1.],
              [6., 0.]])

G = A.dot(F)

print("\nMa trận F:")
print(F)

print("\nMa trận G (kết quả của A.dot(F)):")
print(G)

try:
    A_inv = np.linalg.inv(A)
    print(A_inv)
except np.linalg.LinAlgError as e:
    print(f"Lỗi: {e}.")
    print("Ma trận A là ma trận suy biến (singular matrix), không thể tính nghịch đảo.")
    print("Đây là điều thường xảy ra với ma trận được tạo từ np.arange() mà không có sự xáo trộn.")

A_random = np.random.rand(6, 6)
try:
    A_random_inv = np.linalg.inv(A_random)
    print("Ma trận ngẫu nhiên (A_random):")
    print(A_random)
    print("\nNghịch đảo của A_random:")
    print(A_random_inv)
except np.linalg.LinAlgError:
    print("Ma trận ngẫu nhiên này cũng là suy biến (rất hiếm khi xảy ra với ma trận ngẫu nhiên lớn).")

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận F:
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]

Ma trận G (kết quả của A.dot(F)):
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]
Lỗi: Singular matrix.
Ma trận A là ma trận suy biến (singular matrix), không thể tính nghịch đảo.
Đây là điều thường xảy ra với ma trận được tạo từ np.arange() mà không có sự xáo trộn.
Ma trận ngẫu nhiên (A_random):
[[0.46305765 0.23936402 0.5199007  0.16269463 0.55359564 0.04008829]
 [0.45286748 0.06508371 0.25987099 0.48125857 0.76455101 0.84829305]
 [0.1879672  0.41289859 0.99723716 0.59422665 0.24098689 0.5396773 ]
 [0.1590791  0.8565149  0.83839557 0.9819063  0.10093429 0.56747676]
 [0.13234858 0.38675031 0.79017996 0.63010905 0.09805579 0.55857867]
 [0.45940217 0.6129593  0.36461412 0.35612098 0.06501185 0.14791055]]

Nghịch đảo củ

In [ ]:
import numpy as np

A = np.array([ [1,1],
               [1,0] ])

b = np.array([1, 0])

n = 10

for i in range(n):
    b = A.dot(b)
    print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [ ]:
import sympy as sp
from sympy import Symbol, solve

x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')

pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520

nghiem = sp.solve((pt1, pt2, pt3, pt4), (x1, x2, x3, x4))

print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [ ]:
import numpy as np

A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A:")
print(A)

B = np.zeros((6, 6))
print("\nMa trận B ban đầu (zeroes):")
print(B)

B[0:3, 0:3] = A[0:3, 0:3]

A_flat = A.flatten()

B[0:3, 0:3] = A_flat[0:9].reshape(3, 3)
B[0:3, 3:6] = A_flat[9:18].reshape(3, 3)
B[3:6, 0:3] = A_flat[18:27].reshape(3, 3)
B[3:6, 3:6] = A_flat[27:36].reshape(3, 3)

print("\nMa trận B sau khi gán các khối (sử dụng flatten và reshape):")
print(B)

Ma trận A:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận B ban đầu (zeroes):
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Ma trận B sau khi gán các khối (sử dụng flatten và reshape):
[[ 0.  1.  2.  9. 10. 11.]
 [ 3.  4.  5. 12. 13. 14.]
 [ 6.  7.  8. 15. 16. 17.]
 [18. 19. 20. 27. 28. 29.]
 [21. 22. 23. 30. 31. 32.]
 [24. 25. 26. 33. 34. 35.]]


BAI TAP VE NHA

In [1]:
import numpy as np

def solve_problem_1():

    A = np.array([[1, -1],
                  [2,  3]])
    B = np.array([-2, 6])
    try:
        solution = np.linalg.solve(A, B)

        print(f"  x - y = -2")
        print(f"  2x + 3y = 6")
        print(f"Nghiệm (x, y): {solution}")
        print(f"Vậy, giao điểm là ({solution[0]:.4f}, {solution[1]:.4f})\n")
    except np.linalg.LinAlgError:
        print("Lỗi: Ma trận hệ số không khả nghịch hoặc không vuông.\n")

def solve_problem_2():

    A = np.array([[1, -1,  0],
                  [2, -1, -1],
                  [1,  1,  1]])
    B = np.array([2, 3, 6])
    try:
        solution = np.linalg.solve(A, B)

        print(f"  x - y = 2")
        print(f"  2x - y - z = 3")
        print(f"  x + y + z = 6")
        print(f"Nghiệm (x, y, z): {solution}")
        print(f"Vậy, giao điểm là ({solution[0]:.4f}, {solution[1]:.4f}, {solution[2]:.4f})\n")
    except np.linalg.LinAlgError:
        print("Lỗi: Ma trận hệ số không khả nghịch hoặc không vuông.\n")

def solve_problem_3():

    A = np.array([[1, 1, 1],
                  [4, 2, 1],
                  [9, 3, 1]])
    B = np.array([4, 3, 4])
    try:
        solution = np.linalg.solve(A, B)
        a, b, c = solution
        print(f"Các điều kiện:")
        print(f"  p(1) = 4")
        print(f"  p(2) = 3")
        print(f"  p(3) = 4")
        print(f"Các hệ số (a, b, c): {solution}")
        print(f"Vậy, đa thức bậc hai là: p(x) = {a:.4f}x^2 + {b:.4f}x + {c:.4f}\n")
    except np.linalg.LinAlgError:
        print("Lỗi: Ma trận hệ số không khả nghịch hoặc không vuông.\n")

def solve_problem_4():

    A = np.array([[1,  0, 1],
                  [1,  1, -2],
                  [-2, 2,  1]])
    B = np.array([1, -3, 0])
    try:
        solution = np.linalg.solve(A, B)
        a_pf, b_pf, c_pf = solution
        print(f"Biểu thức gốc: x(x-3) / ((x-1)^2 * (x+2))")
        print(f"Các hệ số phân số từng phần (a, b, c): {solution}")
        print(f"Phân tích phân số từng phần là:")
        print(f"  ({a_pf:.4f})/(x-1) + ({b_pf:.4f})/((x-1)^2) + ({c_pf:.4f})/(x+2)\n")



    except np.linalg.LinAlgError:
        print("Lỗi: Ma trận hệ số không khả nghịch hoặc không vuông.\n")

if __name__ == "__main__":
    solve_problem_1()
    solve_problem_2()
    solve_problem_3()
    solve_problem_4()

  x - y = -2
  2x + 3y = 6
Nghiệm (x, y): [0. 2.]
Vậy, giao điểm là (0.0000, 2.0000)

  x - y = 2
  2x - y - z = 3
  x + y + z = 6
Nghiệm (x, y, z): [3. 1. 2.]
Vậy, giao điểm là (3.0000, 1.0000, 2.0000)

Các điều kiện:
  p(1) = 4
  p(2) = 3
  p(3) = 4
Các hệ số (a, b, c): [ 1. -4.  7.]
Vậy, đa thức bậc hai là: p(x) = 1.0000x^2 + -4.0000x + 7.0000

Biểu thức gốc: x(x-3) / ((x-1)^2 * (x+2))
Các hệ số phân số từng phần (a, b, c): [-0.11111111 -0.66666667  1.11111111]
Phân tích phân số từng phần là:
  (-0.1111)/(x-1) + (-0.6667)/((x-1)^2) + (1.1111)/(x+2)



In [4]:
import sympy

x, y, z = sympy.symbols('x y z')
a, b, c = sympy.symbols('a b c')
expr = x*(x-3) / ((x-1)**2 * (x+2))
print(f"Biểu thức gốc: {expr}")

partial_fraction_decomposition = sympy.apart(expr, x)
print(f"Phân tích phân số từng phần: {partial_fraction_decomposition}")

eq1_coeffs = sympy.Eq(a + c, 1)
eq2_coeffs = sympy.Eq(a + b - 2*c, -3)
eq3_coeffs = sympy.Eq(-2*a + 2*b + c, 0)

coefficients_solution = sympy.solve((eq1_coeffs, eq2_coeffs, eq3_coeffs), (a, b, c))

print(f"Các hệ số (a, b, c) từ giải hệ phương trình: {coefficients_solution}")
a_val = coefficients_solution.get(a)
b_val = coefficients_solution.get(b)
c_val = coefficients_solution.get(c)
print(f"Kiểm tra lại: a={a_val}, b={b_val}, c={c_val}")

integral_result = sympy.integrate(expr, (x, 0, 1))
print(f"Kết quả tích phân từ 0 đến 1: {integral_result}")




Biểu thức gốc: x*(x - 3)/((x - 1)**2*(x + 2))
Phân tích phân số từng phần: 10/(9*(x + 2)) - 1/(9*(x - 1)) - 2/(3*(x - 1)**2)
Các hệ số (a, b, c) từ giải hệ phương trình: {a: -1/9, b: -2/3, c: 10/9}
Kiểm tra lại: a=-1/9, b=-2/3, c=10/9
Kết quả tích phân từ 0 đến 1: -oo + I*pi/9


In [3]:
import numpy as np

def fibonacci(n):
    if n < 0:
        return None
    elif n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        a, b = 0, 1
        for _ in range(2, n + 1):
            a, b = b, a + b
        return b

M = np.array([[1, 1],
              [1, 0]])

for k_val in range(1, 6):
    M_k = np.linalg.matrix_power(M, k_val)

    fib_k_minus_1 = fibonacci(k_val - 1)
    fib_k = fibonacci(k_val)
    fib_k_plus_1 = fibonacci(k_val + 1)

    expected_M_k = np.array([[fib_k_plus_1, fib_k],
                             [fib_k, fib_k_minus_1]])

    print(f"\nVới k = {k_val}:")
    print(f"Ma trận M^{k_val} (tính bằng numpy):")
    print(M_k)
    print(f"Ma trận Fibonacci dự kiến:")
    print(expected_M_k)

    if np.array_equal(M_k, expected_M_k):
        print("=> Chứng minh đúng cho giá trị k này.")
    else:
        print("=> Chứng minh KHÔNG đúng cho giá trị k này (có lỗi xảy ra!).")


Với k = 1:
Ma trận M^1 (tính bằng numpy):
[[1 1]
 [1 0]]
Ma trận Fibonacci dự kiến:
[[1 1]
 [1 0]]
=> Chứng minh đúng cho giá trị k này.

Với k = 2:
Ma trận M^2 (tính bằng numpy):
[[2 1]
 [1 1]]
Ma trận Fibonacci dự kiến:
[[2 1]
 [1 1]]
=> Chứng minh đúng cho giá trị k này.

Với k = 3:
Ma trận M^3 (tính bằng numpy):
[[3 2]
 [2 1]]
Ma trận Fibonacci dự kiến:
[[3 2]
 [2 1]]
=> Chứng minh đúng cho giá trị k này.

Với k = 4:
Ma trận M^4 (tính bằng numpy):
[[5 3]
 [3 2]]
Ma trận Fibonacci dự kiến:
[[5 3]
 [3 2]]
=> Chứng minh đúng cho giá trị k này.

Với k = 5:
Ma trận M^5 (tính bằng numpy):
[[8 5]
 [5 3]]
Ma trận Fibonacci dự kiến:
[[8 5]
 [5 3]]
=> Chứng minh đúng cho giá trị k này.
