bài tập trên lớp

In [1]:
import numpy as np

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))

    return int(ket_qua)

n = 4
X = np.array(range(1, n + 1))
sigma1 = np.array([4, 3, 2, 1])
print(f"For sigma = {sigma1}, sgn_by_def(sigma) = {sgn_by_def(sigma1)}")

sigma2 = np.array([2, 1, 3, 4])
print(f"For sigma = {sigma2}, sgn_by_def(sigma) = {sgn_by_def(sigma2)}")

sigma_identity = np.array([1, 2, 3, 4])
print(f"For sigma = {sigma_identity}, sgn_by_def(sigma) = {sgn_by_def(sigma_identity)}")

sigma_swap = np.array([2, 1, 4, 3])
print(f"For sigma = {sigma_swap}, sgn_by_def(sigma) = {sgn_by_def(sigma_swap)}")

sigma_more_swaps = np.array([1, 4, 3, 2])
print(f"For sigma = {sigma_more_swaps}, sgn_by_def(sigma) = {sgn_by_def(sigma_more_swaps)}")

sigma_three_elements = np.array([3, 1, 2])
print(f"For sigma = {sigma_three_elements}, sgn_by_def(sigma) = {sgn_by_def(sigma_three_elements)}")

For sigma = [4 3 2 1], sgn_by_def(sigma) = 1
For sigma = [2 1 3 4], sgn_by_def(sigma) = -1
For sigma = [1 2 3 4], sgn_by_def(sigma) = 1
For sigma = [2 1 4 3], sgn_by_def(sigma) = 1
For sigma = [1 4 3 2], sgn_by_def(sigma) = -1
For sigma = [3 1 2], sgn_by_def(sigma) = 1


In [2]:
import numpy as np

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))

    return int(ket_qua)

sigma1 = np.array([1, 2, 3, 4])
result1 = sgn_by_def(sigma1)
print(f"sigma = {sigma1}")
print(f"sgn_by_def(sigma) = {result1}")
print(f"Kết quả điền: {result1}")

sigma2 = np.array([4, 3, 2, 1])
result2 = sgn_by_def(sigma2)
print(f"\nsigma = {sigma2}")
print(f"sgn_by_def(sigma) = {result2}")
print(f"Kết quả điền: {result2}")

sigma = [1 2 3 4]
sgn_by_def(sigma) = 1
Kết quả điền: 1

sigma = [4 3 2 1]
sgn_by_def(sigma) = 1
Kết quả điền: 1


In [3]:
from itertools import permutations

n = 3

X = []
for i in range(1, n + 1):
    X.append(i)

Sn = list(permutations(X))

print(Sn)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [4]:
import numpy as np
from itertools import permutations

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))

    return int(ket_qua)

def phatsinh_dinhtuc(n):
    X = []
    for i in range(1, n + 1):
        X.append(i)

    Sn = list(permutations(X))
    dinhtuc = ""

    for sn in Sn:
        sigma = np.array(sn)

        product = ""
        for i in range(n):
            product += "a" + str(i + 1) + str(sn[i])

        dau = sgn_by_def(sigma)

        if (dau == -1):
            product = " - " + product
        else:
            product = " + " + product

        dinhtuc = dinhtuc + product

    return dinhtuc

output_n2 = phatsinh_dinhtuc(2)
print(f"phatsinh_dinhtuc(2)\n'{output_n2}'")

output_n3 = phatsinh_dinhtuc(3)
print(f"\nphatsinh_dinhtuc(3)\n'{output_n3}'")

phatsinh_dinhtuc(2)
' + a11a22 - a12a21'

phatsinh_dinhtuc(3)
' + a11a22a33 - a11a23a32 - a12a21a33 + a12a23a31 + a13a21a32 - a13a22a31'


In [5]:
import numpy as np
from itertools import permutations

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))

    return int(ket_qua)

def phatsinh_dinhtuc(n):
    X = []
    for i in range(1, n + 1):
        X.append(i)

    Sn = list(permutations(X))
    dinhtuc = ""

    for sn in Sn:
        sigma = np.array(sn)

        product = ""
        for i in range(n):
            product += "a" + str(i + 1) + str(sn[i])

        dau = sgn_by_def(sigma)

        if (dau == -1):
            product = " - " + product
        else:
            product = " + " + product

        dinhtuc = dinhtuc + product

    return dinhtuc

result = phatsinh_dinhtuc(3)
print(result)

 + a11a22a33 - a11a23a32 - a12a21a33 + a12a23a31 + a13a21a32 - a13a22a31


In [6]:
import numpy as np
import math
from itertools import permutations

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))

    return int(ket_qua)

def tinhtoan_dinhtuc(A):
    n = A.shape[0]

    X = []
    for i in range(1, n + 1):
        X.append(i)

    Sn = list(permutations(X))

    dinhtuc = 0

    for sn in Sn:
        sigma = np.array(sn)

        product = 1.0

        for i in range(n):
            product = product * A[i][sn[i]-1]

        dau = sgn_by_def(sigma)

        dinhtuc = dinhtuc + (dau * product)

    return dinhtuc

matran = np.array([[3, 5, -8],
                   [4, 12, -1],
                   [2, 5, 3]])

ket_qua_dinhtuc = tinhtoan_dinhtuc(matran)

print(f"Ma trận A:\n{matran}")
print(f"Giá trị định thức của A là: {ket_qua_dinhtuc}")

Ma trận A:
[[ 3  5 -8]
 [ 4 12 -1]
 [ 2  5  3]]
Giá trị định thức của A là: 85.0


In [7]:
import numpy as np
from scipy import linalg

A = np.array([[4, -2],
              [3, -5]])

A1 = np.array([[10, -2],
               [11, -5]])

A2 = np.array([[4, 10],
               [3, 11]])

detA = linalg.det(A)

detA1 = linalg.det(A1)

detA2 = linalg.det(A2)

print(f"detA = {detA}")
print(f"detA1 = {detA1}")
print(f"detA2 = {detA2}")

if detA != 0:
    x1 = detA1 / detA
    x2 = detA2 / detA
    print(f"\nGiá trị của x1 là: {x1}")
    print(f"Giá trị của x2 là: {x2}")
else:
    print("\nĐịnh thức của ma trận A bằng 0. Hệ phương trình có thể không có nghiệm duy nhất.")

detA = -14.0
detA1 = -28.0
detA2 = 14.000000000000004

Giá trị của x1 là: 2.0
Giá trị của x2 là: -1.0000000000000002


In [8]:
import numpy as np
from itertools import permutations

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))

    return int(ket_qua)

def tinhtoan_dinhtuc(A):
    n = A.shape[0]
    X = []
    for i in range(1, n + 1):
        X.append(i)

    Sn = list(permutations(X))
    dinhtuc_val = 0.0

    for sn in Sn:
        sigma = np.array(sn)
        product = 1.0

        for i in range(n):
            product = product * A[i][sn[i]-1]

        dau = sgn_by_def(sigma)
        dinhtuc_val = dinhtuc_val + (dau * product)

    return dinhtuc_val

A = np.array([[4, -2],
              [3, -5]])

A1 = np.array([[10, -2],
               [11, -5]])

A2 = np.array([[4, 10],
               [3, 11]])

detA = tinhtoan_dinhtuc(A)
detA1 = tinhtoan_dinhtuc(A1)
detA2 = tinhtoan_dinhtuc(A2)

if (detA != 0):
    x1 = detA1 / detA
    x2 = detA2 / detA
    print("Hai nghiệm của phương trình là: ", x1, x2)


print(f"detA = {detA}")
print(f"detA1 = {detA1}")
print(f"detA2 = {detA2}")
print(f"x1 = {x1}, x2 = {x2}")

Hai nghiệm của phương trình là:  2.0 -1.0
detA = -14.0
detA1 = -28.0
detA2 = 14.0
x1 = 2.0, x2 = -1.0


In [9]:
import numpy as np
from scipy import linalg
from itertools import permutations

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))
    return int(ket_qua)

def tinhtoan_dinhtuc(A_matrix):
    n = A_matrix.shape[0]
    X = list(range(1, n + 1))

    Sn = list(permutations(X))
    dinhtuc_val = 0.0

    for sn in Sn:
        sigma = np.array(sn)
        product = 1.0

        for i in range(n):
            product = product * A_matrix[i][sn[i]-1]

        dau = sgn_by_def(sigma)
        dinhtuc_val = dinhtuc_val + (dau * product)
    return dinhtuc_val

A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

Ax = np.array([[1, 2, -3],
               [3, -2, 1],
               [2, -4, 4]])

Ay = np.array([[-1, 1, -3],
               [2, 3, 1],
               [3, 2, 4]])

Az = np.array([[-1, 2, 1],
               [2, -2, 3],
               [3, -4, 2]])

print("--- Giải hệ phương trình bằng scipy.linalg.det() ---")
det_A_scipy = linalg.det(A)
det_Ax_scipy = linalg.det(Ax)
det_Ay_scipy = linalg.det(Ay)
det_Az_scipy = linalg.det(Az)

print(f"detA (scipy) = {det_A_scipy}")
print(f"detAx (scipy) = {det_Ax_scipy}")
print(f"detAy (scipy) = {det_Ay_scipy}")
print(f"detAz (scipy) = {det_Az_scipy}")

if det_A_scipy != 0:
    x_scipy = det_Ax_scipy / det_A_scipy
    y_scipy = det_Ay_scipy / det_A_scipy
    z_scipy = det_Az_scipy / det_A_scipy
    print(f"Nghiệm (scipy): x = {x_scipy}, y = {y_scipy}, z = {z_scipy}")
else:
    print("Định thức của ma trận A bằng 0. Hệ phương trình có thể không có nghiệm duy nhất.")

print("\n--- Giải hệ phương trình bằng tinhtoan_dinhtuc() tự định nghĩa ---")
det_A_custom = tinhtoan_dinhtuc(A)
det_Ax_custom = tinhtoan_dinhtuc(Ax)
det_Ay_custom = tinhtoan_dinhtuc(Ay)
det_Az_custom = tinhtoan_dinhtuc(Az)

print(f"detA (custom) = {det_A_custom}")
print(f"detAx (custom) = {det_Ax_custom}")
print(f"detAy (custom) = {det_Ay_custom}")
print(f"detAz (custom) = {det_Az_custom}")

if det_A_custom != 0:
    x_custom = det_Ax_custom / det_A_custom
    y_custom = det_Ay_custom / det_A_custom
    z_custom = det_Az_custom / det_A_custom
    print(f"Nghiệm (custom): x = {x_custom}, y = {y_custom}, z = {z_custom}")
else:
    print("Định thức của ma trận A bằng 0. Hệ phương trình có thể không có nghiệm duy nhất.")

--- Giải hệ phương trình bằng scipy.linalg.det() ---
detA (scipy) = 0.0
detAx (scipy) = 0.0
detAy (scipy) = 0.0
detAz (scipy) = 0.0
Định thức của ma trận A bằng 0. Hệ phương trình có thể không có nghiệm duy nhất.

--- Giải hệ phương trình bằng tinhtoan_dinhtuc() tự định nghĩa ---
detA (custom) = 0.0
detAx (custom) = 0.0
detAy (custom) = 0.0
detAz (custom) = 0.0
Định thức của ma trận A bằng 0. Hệ phương trình có thể không có nghiệm duy nhất.


In [10]:
import numpy as np
from itertools import permutations

def sgn_by_def(sigma):
    ket_qua = 1.0
    n = len(sigma)
    X = np.array(range(1, n + 1))

    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            denominator = sigma[i] - sigma[j]
            if denominator == 0:
                return 0
            ket_qua = ket_qua * ((X[i] - X[j]) / (denominator))
    return int(ket_qua)

def tinhtoan_dinhtuc(A_matrix):
    n = A_matrix.shape[0]
    X = list(range(1, n + 1))

    Sn = list(permutations(X))
    dinhtuc_val = 0.0

    for sn in Sn:
        sigma = np.array(sn)
        product = 1.0

        for i in range(n):
            product = product * A_matrix[i][sn[i]-1]

        dau = sgn_by_def(sigma)
        dinhtuc_val = dinhtuc_val + (dau * product)
    return dinhtuc_val

A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

Ax = np.array([[1, 2, -3],
               [3, -2, 1],
               [2, -4, 4]])

Ay = np.array([[-1, 1, -3],
               [2, 3, 1],
               [3, 2, 4]])

Az = np.array([[-1, 2, 1],
               [2, -2, 3],
               [3, -4, 2]])

det = tinhtoan_dinhtuc(A)
detX = tinhtoan_dinhtuc(Ax)
detY = tinhtoan_dinhtuc(Ay)
detZ = tinhtoan_dinhtuc(Az)

if det != 0:
    x = detX / det
    y = detY / det
    z = detZ / det

    print(f"Nghiệm, x = {x}, y = {y}, z = {z}")
else:
    print("Định thức của ma trận hệ số bằng 0. Hệ phương trình có thể không có nghiệm duy nhất.")

Định thức của ma trận hệ số bằng 0. Hệ phương trình có thể không có nghiệm duy nhất.


In [11]:
import sympy as sp

TG = sp.Matrix([[1, 0, 1],
                [4, 3, 1],
                [2, 2, 1]])

result = (1/2) * TG.det()

print(result)

1.50000000000000


In [12]:
import sympy as sp

M = sp.Matrix([[0, 4, 1, 1],
               [4, 0, 0, 1],
               [3, 5, 2, 1],
               [2, 2, 5, 1]])

det_M = M.det()
print(det_M)

result = (1/6) * M.det()
print(result)

-72
-12.0000000000000


bài tập về nhà

In [13]:
import numpy as np
from scipy import linalg

def get_minor_matrix(matrix, i, j):
    return np.delete(np.delete(matrix, i, axis=0), j, axis=1)

def calculate_cofactor(matrix, i, j):
    minor_matrix = get_minor_matrix(matrix, i, j)
    if minor_matrix.shape == (1, 1):
        det_minor = minor_matrix[0, 0]
    else:
        det_minor = linalg.det(minor_matrix)

    return ((-1)**(i + j)) * det_minor

def calculate_cofactor_matrix(matrix):
    n = matrix.shape[0]
    cofactor_matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            cofactor_matrix[i, j] = calculate_cofactor(matrix, i, j)
    return cofactor_matrix

def calculate_adjoint_matrix(matrix):
    cofactor_mat = calculate_cofactor_matrix(matrix)
    return cofactor_mat.T

if __name__ == "__main__":
    A_2x2 = np.array([[4, 7],
                      [2, 6]])
    print(A_2x2)

    cofactor_A_2x2 = calculate_cofactor_matrix(A_2x2)
    print(cofactor_A_2x2)

    adjoint_A_2x2 = calculate_adjoint_matrix(A_2x2)

    print(adjoint_A_2x2)

    A_3x3 = np.array([[-1, 2, -3],
                      [2, -2, 1],
                      [3, -4, 4]])
    print("\n--- Ma trận A (3x3) ---")
    print(A_3x3)

    cofactor_A_3x3 = calculate_cofactor_matrix(A_3x3)

    print(cofactor_A_3x3)

    adjoint_A_3x3 = calculate_adjoint_matrix(A_3x3)

    print(adjoint_A_3x3)

--- Ma trận A (2x2) ---
[[4 7]
 [2 6]]

a. Ma trận hệ số kép (Cofactor Matrix) của A (2x2):
[[ 6. -2.]
 [-7.  4.]]

b. Ma trận liên hợp (Adjoint Matrix) của A (2x2):
[[ 6. -7.]
 [-2.  4.]]

--- Ma trận A (3x3) ---
[[-1  2 -3]
 [ 2 -2  1]
 [ 3 -4  4]]

a. Ma trận hệ số kép (Cofactor Matrix) của A (3x3):
[[-4. -5. -2.]
 [ 4.  5.  2.]
 [-4. -5. -2.]]

b. Ma trận liên hợp (Adjoint Matrix) của A (3x3):
[[-4.  4. -4.]
 [-5.  5. -5.]
 [-2.  2. -2.]]


In [17]:
import sympy as sp

# Khai báo biến
x, y = sp.symbols('x y')
x1, y1 = sp.symbols('x1 y1')
x2, y2 = sp.symbols('x2 y2')
x3, y3 = sp.symbols('x3 y3')

# Tạo ma trận theo định thức đã cho
M = sp.Matrix([
    [x**2 + y**2, x, y, 1],
    [x1**2 + y1**2, x1, y1, 1],
    [x2**2 + y2**2, x2, y2, 1],
    [x3**2 + y3**2, x3, y3, 1]
])

# Tính định thức
det = M.det()

# Hiển thị phương trình đường tròn
print("Phương trình đường tròn là:")
sp.pprint(sp.Eq(det, 0))


Phương trình đường tròn là:
 2          2          2          2          2          2             2        ↪
x ⋅x₁⋅y₂ - x ⋅x₁⋅y₃ - x ⋅x₂⋅y₁ + x ⋅x₂⋅y₃ + x ⋅x₃⋅y₁ - x ⋅x₃⋅y₂ - x⋅x₁ ⋅y₂ + x ↪

↪    2          2          2          2          2          2          2       ↪
↪ ⋅x₁ ⋅y₃ + x⋅x₂ ⋅y₁ - x⋅x₂ ⋅y₃ - x⋅x₃ ⋅y₁ + x⋅x₃ ⋅y₂ - x⋅y₁ ⋅y₂ + x⋅y₁ ⋅y₃ +  ↪

↪        2          2       2             2     2          2           2       ↪
↪ x⋅y₁⋅y₂  - x⋅y₁⋅y₃  - x⋅y₂ ⋅y₃ + x⋅y₂⋅y₃  + x₁ ⋅x₂⋅y - x₁ ⋅x₂⋅y₃ - x₁ ⋅x₃⋅y  ↪

↪     2              2          2           2          2          2          2 ↪
↪ + x₁ ⋅x₃⋅y₂ - x₁⋅x₂ ⋅y + x₁⋅x₂ ⋅y₃ + x₁⋅x₃ ⋅y - x₁⋅x₃ ⋅y₂ + x₁⋅y ⋅y₂ - x₁⋅y  ↪

↪              2          2        2              2     2          2           ↪
↪ ⋅y₃ - x₁⋅y⋅y₂  + x₁⋅y⋅y₃  + x₁⋅y₂ ⋅y₃ - x₁⋅y₂⋅y₃  + x₂ ⋅x₃⋅y - x₂ ⋅x₃⋅y₁ - x ↪

↪     2          2          2          2             2          2        2     ↪
↪ ₂⋅x₃ ⋅y + x₂⋅x₃ ⋅y₁ - x₂⋅y ⋅y₁ + x₂⋅y ⋅y₃ + x₂⋅y⋅y₁  - x₂⋅y⋅y₃  - x₂⋅y₁ ⋅y