In [ ]:
import numpy as np
D = np.array([[1,2],[3,4]])
E = np.zeros_like(D)
np.copyto(E, D)
print(E)
D_for_block2 = np.array([[1,2],[3,4]])
E_initial = np.array([[1,2],[3,5]])
np.copyto(E_initial, D_for_block2)
print(E_initial)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
import numpy as np

D = np.array([[1,2],[3,4]])
E = np.zeros_like(D)
np.copyto(E, D)
print(E)

D_for_block2 = np.array([[1,2],[3,4]])
E_initial = np.array([[1,2],[3,5]])

np.copyto(E_initial, D_for_block2)
print(E_initial)


C_corrected_as_strings = np.array([['value_from_x', 'value_from_y'], ['1_str', '2_str']], dtype=str)
print(C_corrected_as_strings)
print("dtype:", C_corrected_as_strings.dtype)

x = np.array([['a','b'],['c','d']])
y = 'x'
C_corrected_object_type = np.array([[x,y],[1, 2]], dtype=object)
print(C_corrected_object_type)
print("dtype:", C_corrected_object_type.dtype)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[['value_from_x' 'value_from_y']
 ['1_str' '2_str']]
dtype: <U12
[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]
dtype: object


In [ ]:
import numpy as np

A_corrected_2d_matrix = np.matrix([[1,2,3,4],[5,6,7,8]])
print(A_corrected_2d_matrix)
print("Shape:", A_corrected_2d_matrix.shape)
print("-" * 30)

A_np_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A_np_array)
print("Shape:", A_np_array.shape)
print("Kiểu dữ liệu (dtype):", A_np_array.dtype)

[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Kiểu dữ liệu (dtype): int64


In [ ]:
import numpy as np
import numpy.matlib as matlib

G = matlib.identity(5)
print(G)
print("Shape:", G.shape)

H = matlib.randn(3,2)
print(H)
print("Shape:", H.shape)

K = matlib.zeros((4,4))
print(K)
print("Shape:", K.shape)

D = np.array([[1,2],[3,4]])
E_fixed_block1 = np.zeros_like(D)
np.copyto(E_fixed_block1, D)
print(E_fixed_block1)
print("Shape:", E_fixed_block1.shape)

E_block2_initial = np.array([[1,2],[3,5]])
np.copyto(E_block2_initial, D)
print(E_block2_initial)
print("Shape:", E_block2_initial.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape: (5, 5)
[[-0.42261044  0.12226672]
 [-1.02465538  0.31372592]
 [ 0.49950734  0.27311125]]
Shape: (3, 2)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (4, 4)
[[1 2]
 [3 4]]
Shape: (2, 2)
[[1 2]
 [3 4]]
Shape: (2, 2)


In [ ]:
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]

M = np.array([[1,2],[3,4]])

for i in range(len(c)):
    ci = np.array([[1,1],[1,0]])
    ci[0, 0] = c[i]

    if (i == 0):
        M = ci
    else:
        M = np.dot(M, ci)

print("Ma trận M cuối cùng:")
print(M)
print("Giá trị gần đúng của Pi theo dãy liên phân số:")
print(M[0,0] / M[1,0])

c_short = [3, 7, 15]
M_short = np.array([[1,2],[3,4]])

for i in range(len(c_short)):
    ci_short = np.array([[1,1],[1,0]])
    ci_short[0, 0] = c_short[i]

    if (i == 0):
        M_short = ci_short
    else:
        M_short = np.dot(M_short, ci_short)

print("Ma trận M cuối cùng (c_short):")
print(M_short)
print("Giá trị gần đúng của Pi (c_short):")
print(M_short[0,0] / M_short[1,0])

D = np.array([[1,2],[3,4]])
E = np.zeros_like(D)
np.copyto(E, D)
print("Kết quả sau khi sửa lỗi cho đoạn 1:")
print(E)

D_for_block2 = np.array([[1,2],[3,4]])

E = np.array([[1,2],[3,5]])
np.copyto(E, D_for_block2)
print("Kết quả sau khi sửa lỗi/chạy cho đoạn 2:")
print(E)

Ma trận M cuối cùng:
[[165707065  80143857]
 [ 52746197  25510582]]
Giá trị gần đúng của Pi theo dãy liên phân số:
3.1415926535897936
Ma trận M cuối cùng (c_short):
[[333  22]
 [106   7]]
Giá trị gần đúng của Pi (c_short):
3.141509433962264
Kết quả sau khi sửa lỗi cho đoạn 1:
[[1 2]
 [3 4]]
Kết quả sau khi sửa lỗi/chạy cho đoạn 2:
[[1 2]
 [3 4]]


In [ ]:
import numpy as np

X = np.array([[1, 1],
              [1, 2],
              [1, 3]])

Y = np.array([1.0, 2.2, 3.4])

XT = X.T

print("Ma trận X:")
print(X)
print("\nVector Y:")
print(Y)
print("\nMa trận chuyển vị X^T:")
print(XT)

D = np.array([[1,2],[3,4]])

E_fixed_1 = np.zeros_like(D)
np.copyto(E_fixed_1, D)
print(E_fixed_1)

D_for_block2 = np.array([[1,2],[3,4]])

E_initial_2 = np.array([[1,2],[3,5]])
np.copyto(E_initial_2, D_for_block2)
print(E_initial_2)

Ma trận X:
[[1 1]
 [1 2]
 [1 3]]

Vector Y:
[1.  2.2 3.4]

Ma trận chuyển vị X^T:
[[1 1 1]
 [1 2 3]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
import numpy as np

X = np.array([[1, 1],
              [1, 2],
              [1, 3]])

Y = np.array([1.0, 2.2, 3.4])

XT = X.T

XTX = XT @ X
A1 = np.linalg.inv(XTX)

A2 = XT @ Y

print("Giá trị A1 = (X^T X)^-1:")
print(A1)
print("\nGiá trị A2 = X^T Y:")
print(A2)

beta_hat = A1 @ A2
print(beta_hat)

D = np.array([[1,2],[3,4]])

E_fixed_1 = np.zeros_like(D)
np.copyto(E_fixed_1, D)
print(E_fixed_1)

E_initial_2 = np.array([[1,2],[3,5]])
np.copyto(E_initial_2, D)
print(E_initial_2)

Giá trị A1 = (X^T X)^-1:
[[ 2.33333333 -1.        ]
 [-1.          0.5       ]]

Giá trị A2 = X^T Y:
[ 6.6 15.6]
[-0.2  1.2]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
import numpy as np

X = np.array([[1, 1],
              [1, 2],
              [1, 3]])

Y = np.array([1.0, 2.2, 3.4])

XT = X.T
XTX = XT @ X
A1 = np.linalg.inv(XTX)
A2 = XT @ Y

A_coeffs = A1.dot(A2)
print(A_coeffs)

a0 = A_coeffs[0]
a1 = A_coeffs[1]
print(f"f(x) = {a0:.4f} + {a1:.4f}x")

D = np.array([[1,2],[3,4]])

E_fixed_1 = np.zeros_like(D)
np.copyto(E_fixed_1, D)
print(E_fixed_1)

E_initial_2 = np.array([[1,2],[3,5]])
np.copyto(E_initial_2, D)
print(E_initial_2)

[-0.2  1.2]
f(x) = -0.2000 + 1.2000x
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


bài tập chương

In [ ]:
import numpy as np

x_data = np.array([0, 1, 2, 3, 4])
y_data = np.array([10, 8, 7, 5, 2])

n = len(x_data)

sum_x = np.sum(x_data)
sum_y = np.sum(y_data)

sum_xy = np.sum(x_data * y_data)

sum_x_squared = np.sum(x_data**2)

numerator_a = n * sum_xy - sum_x * sum_y
denominator_a = n * sum_x_squared - (sum_x)**2
a = numerator_a / denominator_a

b = (sum_y - a * sum_x) / n

print(f"Phương trình tuyến tính: y = {b:.1f} + {a:.1f}x")

Phương trình tuyến tính: y = 10.2 + -1.9x
