In [ ]:
bài tập lớp

In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a, b)  # tích vô hướng
print(tich)


32


In [2]:
import numpy as np
a = np.array([1, 2, -3])
print(np.linalg.norm(a))


3.7416573867739413


In [3]:
import numpy as np
a = np.array([1, 2, -3])
print(np.linalg.norm(a, 1))


6.0


In [4]:
import math
import numpy as np

def chuan(a, p):
    return np.linalg.norm(a, ord=p)

a = np.array([1, 2, -3])
print(chuan(a, 1))


6.0


In [5]:
np.linalg.norm(a, 1)


np.float64(6.0)

In [6]:
chuan(a, 2)

np.float64(3.7416573867739413)

In [7]:
np.linalg.norm(a,2)

np.float64(3.7416573867739413)

In [8]:
 chuan(a, 3)

np.float64(3.3019272488946263)

In [9]:
np.linalg.norm(a,3)

np.float64(3.3019272488946263)

In [10]:
 chuan(a, 1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [11]:
 np.linalg.norm(a,1000)

np.float64(inf)

In [13]:
from scipy import linalg
linalg.norm(a)

np.float64(3.7416573867739413)

In [14]:
 linalg.norm(a, 100)

np.float64(3.0)

In [15]:
 linalg.norm(a, 1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [16]:
import numpy as np

m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])

M = np.array([v1, v2, v3, v4])
MT = M.transpose()

print(MT)


[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]


In [19]:
 v = (1.0/m)*MT.dot(mi)


In [20]:
 print (v)

[1.3 0.9 0. ]


In [21]:
import numpy as np

A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

x0 = np.array([0.95, 0.05])

A_100 = np.linalg.matrix_power(A, 100)

x_100 = A_100 @ x0

print(x_100)


[0.98550723 0.01449277]


In [22]:
import numpy as np

A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

v0 = np.array([0.95, 0.05])

A_100 = np.linalg.matrix_power(A, 100)

v100 = A_100 @ v0

print(v100)


[0.98550723 0.01449277]


In [23]:
import sympy as sym

x, y = sym.symbols('x y')
xy = sym.Matrix([x, y])
A = sym.Matrix([[1, -68], [1, 1]])
v = sym.Matrix([0, 1])

nghiem = sym.solve([A * xy - v])
print(sym.pretty(nghiem))


⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [24]:
import numpy as np

A = np.array([[1, 6],
              [5, 2]])

u = np.array([-5, 6])

Au = A @ u
lam_u = -4 * u

print(Au)
print(lam_u)
print(np.allclose(Au, lam_u))


[ 31 -13]
[ 20 -24]
False


In [25]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2, 3], [3, -6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda * I - A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu, 4) for phantu in nghiem])


[-7.000, 3.000]


In [26]:
 print (sympy.pretty(nghiem))

[-7, 3]


In [27]:
import sympy

x, y = sympy.symbols('x y')
A = sympy.Matrix([[2, 3], [3, -6]])
lambda_val = 3
I = sympy.eye(2)

B = A - lambda_val * I
v = sympy.Matrix([x, y])

phuongtrinh = B * v
nghiem = sympy.solve(phuongtrinh, (x, y), dict=True)
print(nghiem)


[{x: 3*y}]


In [28]:
import numpy as np
from numpy import linalg as LA

A = np.array([[2, 3],
              [3, -6]])

D = np.array([[-7, 0],
              [0, 3]])

P = np.array([[-1.0/3, 3],
              [1, 1]])

P1 = LA.inv(P)
print(P1)


[[-0.3  0.9]
 [ 0.3  0.1]]


In [29]:
A.dot(P)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [30]:
P.dot(D)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [31]:
 print (D **2)

[[49  0]
 [ 0  9]]


bài tập nhà

câu 1: đáp án đúng là a,b,c


In [32]:
import numpy as np

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
p = np.array([2, 3, 4])

khoang_cach = np.linalg.norm(u - v)
print(khoang_cach)

cos_theta = np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)
print(theta_rad)
print(theta_deg)

proj_p_on_v = (np.dot(p, v) / np.dot(v, v)) * v
print(proj_p_on_v)


5.196152422706632
0.2257261285527342
12.933154491899135
[2.44155844 3.05194805 3.66233766]
