cau 1

In [1]:
import numpy as np
import math

A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])

tong_AB = A + B
tich_so = 3 * A - 2 * B
print("Câu 1a:")
print("Tổng A + B:", tong_AB)
print("Tích số 3A - 2B:", tich_so)

dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_rad = math.acos(cos_theta)
angle_deg = math.degrees(angle_rad)
print("\nCâu 1b:")
print("Tích vô hướng A · B:", dot_product)
print("Góc giữa A và B (độ):", round(angle_deg, 3))

CTC = np.dot(C.T, C)
print("\nCâu 1c:")
print("Ma trận Cᵀ * C:\n", CTC)


Câu 1a:
Tổng A + B: [3 3 1 5]
Tích số 3A - 2B: [  4 -11  13 -10]

Câu 1b:
Tích vô hướng A · B: -8
Góc giữa A và B (độ): 108.376

Câu 1c:
Ma trận Cᵀ * C:
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


cau 2

In [2]:
import numpy as np

M = np.array([[1, 2, 3, 0], [4, 5, 6, 1], [7, 8, 9, 2], [0, 1, 1, 0]])
N = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

MN = np.dot(M, N)
print("Câu 2a:")
print("Tích M × N:\n", MN)

try:
    det_M = np.linalg.det(M)
    print("\nCâu 2b:")
    print("Định thức của M:", round(det_M, 3))
except:
    print("\nKhông thể tính định thức vì M không phải là ma trận vuông.")

rank_N = np.linalg.matrix_rank(N)
print("\nCâu 2c:")
print("Hạng của ma trận N:", rank_N)


Câu 2a:
Tích M × N:
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

Câu 2b:
Định thức của M: 0.0

Câu 2c:
Hạng của ma trận N: 2


cau 3

In [3]:
import numpy as np

P = np.array([[2, 1, 0, 1], [0, 3, 1, -1], [1, 0, 4, 2], [0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])

try:
    P_inv = np.linalg.inv(P)
    print("Câu 3a:")
    print("Ma trận nghịch đảo của P:\n", P_inv)
except np.linalg.LinAlgError:
    print("Ma trận P không khả nghịch.")

x = np.dot(P_inv, b)
print("\nCâu 3b:")
print("Nghiệm của hệ phương trình:", x)

Ax = np.dot(P, x)
print("\nCâu 3c:")
print("P * x =", Ax)
print("Vector b =", b)
print("Kiểm tra đúng:", np.allclose(Ax, b))


Câu 3a:
Ma trận nghịch đảo của P:
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

Câu 3b:
Nghiệm của hệ phương trình: [0.46511628 2.10465116 1.65116279 0.96511628]

Câu 3c:
P * x = [4. 7. 9. 5.]
Vector b = [4 7 9 5]
Kiểm tra đúng: True


cau 4

In [4]:
import numpy as np

Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(Q)
print("Câu 4a:")
print("Giá trị riêng:", eigenvalues)

print("\nCâu 4b:")
print("Các vector riêng cột tương ứng:\n", eigenvectors)

norm_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("\nCâu 4c:")
print("Vector riêng chuẩn hóa (dài bằng 1):\n", norm_vectors)


Câu 4a:
Giá trị riêng: [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]

Câu 4b:
Các vector riêng cột tương ứng:
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]

Câu 4c:
Vector riêng chuẩn hóa (dài bằng 1):
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743+0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]


cau 5

In [5]:
import numpy as np

R = np.array([[1, -2, 3],
              [2, 0, 1],
              [-1, 1, 4]])
b = np.array([10, 8, 7])

x1 = np.linalg.solve(R, b)
print("Câu 5a:")
print("Nghiệm hệ Rx = b:", x1)

det_R = np.linalg.det(R)
print("\nCâu 5b:")
print("Định thức của R:", round(det_R, 3))

if not np.isclose(det_R, 0):
    R_inv = np.linalg.inv(R)
    x2 = R_inv @ b
    print("Ma trận nghịch đảo R⁻¹:\n", R_inv)
    print("Nghiệm bằng R⁻¹ · b:", x2)
    print("So sánh hai nghiệm giống nhau:", np.allclose(x1, x2))
else:
    print("Ma trận R không khả nghịch.")

fro_norm = np.linalg.norm(R, 'fro')
print("\nCâu 5c:")
print("Chuẩn Frobenius của R:", round(fro_norm, 3))


Câu 5a:
Nghiệm hệ Rx = b: [2.7826087  0.04347826 2.43478261]

Câu 5b:
Định thức của R: 23.0
Ma trận nghịch đảo R⁻¹:
 [[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
Nghiệm bằng R⁻¹ · b: [2.7826087  0.04347826 2.43478261]
So sánh hai nghiệm giống nhau: True

Câu 5c:
Chuẩn Frobenius của R: 6.083
